spring:
  application:
    name: books-service
  cloud:
    azure:
      active-directory:
        enabled: true
        credential:
          client-id: ed89fb04-ca69-45dc-ae83-990b7f21cb11
        app-id-uri: api://books
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
